name: npm publish

on: 
 push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 22.x
        
    - name: npm publish
      run: |
        cd ./cli
        npm run log
        npm publish
