name: npm publish

on:
  push:
    tags:
      - "v*"
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  publish:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
          
      - name: Set Publishing Config
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: npm publish
        run: |
          cd ./cli
          # npm publish -r --tag latest --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release and Upload Release Asset
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.ReleaseVersion }}
          title: ${{ env.ReleaseVersion }}
          prerelease: false

